### ISSUE TITLE
No lineage returned for renku run ... <output folder>

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-graph#172] opened 2019-11-06 10:31 UTC
# Description

If a script is implemented to take an output folder as an argument and write files into the output folder, the command line correctly records lineage, but the linage returned by the graph is not correct.

# Example:

This file has no lineage in the graph:

https://dev.renku.ch/projects/cramakri/folder-output-test/files/lineage/data/output/count.csv

The response from the graph is: 

```json
{"data":{"lineage":null}}
```

But `renku log` returns this:

```
$ renku log
*  8d7ddaac data/output/count.csv
|           (part of data/output directory)
*    8d7ddaac data/output
|\            (part of data directory)
@ |  8d7ddaac data
 /
*    8d7ddaac .renku/workflow/619855359887402f8ae14532c37babdb_python.cwl
|\
* |  a7900729 src/python/run.py
| |           (part of src/python directory)
* |  a7900729 src/python
| |           (part of src directory)
@ |  a7900729 src
 /
*  9432c333 data/input/input.csv
|           (part of data/input directory)
*  9432c333 data/input
|           (part of data directory)
@  9432c333 (latest -> 8d7ddaac) data
```

**Comment by jachro** [comment] 2020-02-21 16:51
Unfortunately, this project does not exist anymore but from the description it looks it's a duplicate of https://github.com/SwissDataScienceCenter/renku-graph/issues/241.

**Closed by jachro** 2020-02-21 16:51 UTC
Labels: bug, user
